INSERT INTO palateapp.countrydetails values (1 ,'INDIA' ,91 ,'INR' ,'RUPEE', 'IND' ,'U+20B9');
INSERT INTO palateapp.countrydetails values (2 ,'UNITED STATES OF AMERICA' ,1 ,'USD' ,'DOLLAR ', 'USA' ,'');
INSERT INTO palateapp.countrydetails values (3 ,'AUSTRALIA' ,61 ,'AUD' ,'DOLLAR ', 'AUS' ,'');
INSERT INTO palateapp.countrydetails values (4 ,'NEW ZEALAND' ,64 ,'NZD' ,'DOLLAR ', 'NZL' ,'');
INSERT INTO palateapp.countrydetails values (5 ,'ALBANIA' ,355 ,'ALL' ,'LEK', 'ALB' ,'');
INSERT INTO palateapp.countrydetails values (6 ,'ANDORRA' ,376 ,'EUR' ,'EURO', 'AND' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (7 ,'AUSTRIA' ,43 ,'EUR' ,'EURO', 'AUT' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (8 ,'BELARUS' ,375 ,'BYR' ,'RUBLE', 'BLR' ,'');
INSERT INTO palateapp.countrydetails values (9 ,'BELGIUM' ,32 ,'EUR' ,'EURO', 'BEL' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (10 ,'BOSNIA AND HERZEGOVINA' ,387 ,'BAM' ,'MARKA', 'BIH' ,'');
INSERT INTO palateapp.countrydetails values (11 ,'BULGARIA' ,359 ,'EUR' ,'EURO', 'BGR' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (12 ,'CROATIA' ,385 ,'EUR' ,'EURO', 'HRV' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (13 ,'CZECH REPUBLIC (CZECHIA)' ,420 ,'EUR' ,'EURO', 'CZE' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (14 ,'DENMARK' ,45 ,'EUR' ,'EURO', 'DNK' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (15 ,'ESTONIA' ,372 ,'EUR' ,'EURO', 'EST' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (16 ,'FINLAND' ,358 ,'EUR' ,'EURO', 'FIN' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (17 ,'FRANCE' ,33 ,'EUR' ,'EURO', 'FRA' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (18 ,'GERMANY' ,49 ,'EUR' ,'EURO', 'DEU' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (19 ,'GREECE' ,30 ,'EUR' ,'EURO', 'GRC' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (20 ,'HOLY SEE (VATICAN CITY STATE)' ,379 ,'EUR' ,'EURO', 'VAT' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (21 ,'HUNGARY' ,36 ,'EUR' ,'EURO', 'HUN' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (22 ,'ICELAND' ,354 ,'ISK' ,'KRONA', 'ISL' ,'');
INSERT INTO palateapp.countrydetails values (23 ,'IRELAND' ,353 ,'EUR' ,'EURO', 'IRL' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (24 ,'ITALY' ,39 ,'EUR' ,'EURO', 'ITA' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (25 ,'LATVIA' ,371 ,'EUR' ,'EURO', 'LVA' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (26 ,'LIECHTENSTEIN' ,423 ,'CHF' ,'FRANC', 'LIE' ,'');
INSERT INTO palateapp.countrydetails values (27 ,'LITHUANIA' ,370 ,'EUR' ,'EURO', 'LTU' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (28 ,'LUXEMBOURG' ,352 ,'EUR' ,'EURO', 'LUX' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (29 ,'MALTA' ,356 ,'EUR' ,'EURO', 'MLT' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (30 ,'MOLDOVA' ,373 ,'MDL' ,'LEU', 'MDA' ,'');
INSERT INTO palateapp.countrydetails values (31 ,'MONACO' ,377 ,'EUR' ,'EURO', 'MCO' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (32 ,'MONTENEGRO' ,382 ,'EUR' ,'EURO', 'MNE' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (33 ,'NETHERLANDS' ,31 ,'EUR' ,'EURO', 'NLD' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (34 ,'NORTH MACEDONIA' ,389 ,'MKD' ,'DENAR ', 'MKD' ,'');
INSERT INTO palateapp.countrydetails values (35 ,'NORWAY' ,47 ,'NOK' ,'KRONE ', 'NOR' ,'');
INSERT INTO palateapp.countrydetails values (36 ,'POLAND' ,48 ,'EUR' ,'EURO', 'POL' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (37 ,'PORTUGAL' ,351 ,'EUR' ,'EURO', 'PRT' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (38 ,'ROMANIA' ,40 ,'EUR' ,'EURO', 'ROU' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (39 ,'RUSSIA' ,7 ,'RUB' ,'RUBLE ', 'RUS' ,'');
INSERT INTO palateapp.countrydetails values (40 ,'SAN MARINO' ,378 ,'EUR' ,'EURO', 'SMR' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (41 ,'SERBIA' ,381 ,'RSD' ,'DINAR ', 'SRB' ,'');
INSERT INTO palateapp.countrydetails values (42 ,'SLOVAKIA' ,421 ,'EUR' ,'EURO', 'SVK' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (43 ,'SLOVENIA' ,386 ,'EUR' ,'EURO', 'SVN' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (44 ,'SPAIN' ,34 ,'EUR' ,'EURO', 'ESP' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (45 ,'SWEDEN' ,46 ,'EUR' ,'EURO', 'SWE' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (46 ,'SWITZERLAND' ,41 ,'CHF' ,'FRANC ', 'CHE' ,'');
INSERT INTO palateapp.countrydetails values (47 ,'UKRAINE' ,380 ,'UAH' ,'HRYVNIA ', 'UKR' ,'');
INSERT INTO palateapp.countrydetails values (48 ,'UNITED KINGDOM' ,44 ,'GBP' ,'POUND ', 'GBR' ,'U+00A3');
INSERT INTO palateapp.countrydetails values (49 ,'GIBRALTAR' ,350 ,'GIP' ,'POUND ', 'GIB' ,'');
INSERT INTO palateapp.countrydetails values (50 ,'ISLE OF MAN' ,44 ,'GBP' ,'POUND ', 'IMN' ,'U+00A3');
INSERT INTO palateapp.countrydetails values (51 ,'TURKEY' ,90 ,'TRY' ,'LIRA ', 'TUR' ,'');
INSERT INTO palateapp.countrydetails values (52 ,'ARMENIA' ,374 ,'AMD' ,'DRAM ', 'ARM' ,'');
INSERT INTO palateapp.countrydetails values (53 ,'FAROE ISLANDS' ,298 ,'DKK' ,'KRONE ', 'FRO' ,'');
INSERT INTO palateapp.countrydetails values (54 ,'GEORGIA' ,995 ,'GEL' ,'LARI ', 'GEO' ,'');
INSERT INTO palateapp.countrydetails values (55 ,'KOSOVO' ,381 ,'EUR' ,'EURO', 'XKX' ,'U+20AC');
INSERT INTO palateapp.countrydetails values (56 ,'CYPRUS' ,357 ,'EUR' ,'EURO', 'CYP' ,'U+20AC');
