INSERT INTO palateapp.countrydetails values (1, 'AFGHANISTAN', 93, 'AFN','Afghan Afghani','AF','');
INSERT INTO palateapp.countrydetails values (2, 'ALBANIA', 355, 'ALL','Albanian Lek','AL','');
INSERT INTO palateapp.countrydetails values (3, 'ALGERIA', 213, 'DZD','Algerian Dinar','DZ','');
INSERT INTO palateapp.countrydetails values (4, 'ANDORRA', 376, 'EUR','Euro','AD','U+20AC');
INSERT INTO palateapp.countrydetails values (5, 'ANGOLA', 244, 'AOA','Angolan Kwanza','AO','');
INSERT INTO palateapp.countrydetails values (6, 'ANTIGUA AND BARBUDA', 1, 'XCD','East Caribbean Dollar','AG','');
INSERT INTO palateapp.countrydetails values (7, 'ARGENTINA', 54, 'ARS','Argentine Peso','AR','');
INSERT INTO palateapp.countrydetails values (8, 'ARMENIA', 374, 'AMD','Armenian Dram','AM','');
INSERT INTO palateapp.countrydetails values (9, 'AUSTRALIA', 61, 'AUD','Australian Dollar','AU','');
INSERT INTO palateapp.countrydetails values (10, 'AUSTRIA', 43, 'EUR','Euro','AT','U+20AC');
INSERT INTO palateapp.countrydetails values (11, 'AZERBAIJAN', 994, 'AZN','Azerbaijani Manat','AZ','');
INSERT INTO palateapp.countrydetails values (12, 'BAHAMAS', 1, 'BSD','Bahamian Dollar','BS','');
INSERT INTO palateapp.countrydetails values (13, 'BAHRAIN', 973, 'BHD','Bahraini Dinar','BH','');
INSERT INTO palateapp.countrydetails values (14, 'BANGLADESH', 880, 'BDT','Bangladeshi Taka','BD','');
INSERT INTO palateapp.countrydetails values (15, 'BARBADOS', 1, 'BBD','Barbadian Dollar','BB','');
INSERT INTO palateapp.countrydetails values (16, 'BELARUS', 375, 'BYN','Belarusian Ruble','BY','');
INSERT INTO palateapp.countrydetails values (17, 'BELGIUM', 32, 'EUR','Euro','BE','U+20AC');
INSERT INTO palateapp.countrydetails values (18, 'BELIZE', 501, 'BZD','Belize Dollar','BZ','');
INSERT INTO palateapp.countrydetails values (19, 'BENIN', 229, 'XOF','West African CFA Franc','BJ','');
INSERT INTO palateapp.countrydetails values (20, 'BHUTAN', 975, 'BTN','Bhutanese Ngultrum','BT','');
INSERT INTO palateapp.countrydetails values (21, 'BOLIVIA', 591, 'BOB','Bolivian Boliviano','BO','');
INSERT INTO palateapp.countrydetails values (22, 'BOSNIA AND HERZEGOVINA', 387, 'BAM','Bosnia and Herzegovina Convertible Mark','BA','');
INSERT INTO palateapp.countrydetails values (23, 'BOTSWANA', 267, 'BWP','Botswana Pula','BW','');
INSERT INTO palateapp.countrydetails values (24, 'BRAZIL', 55, 'BRL','Brazilian Real','BR','');
INSERT INTO palateapp.countrydetails values (25, 'BRUNEI', 673, 'BND','Brunei Dollar','BN','');
INSERT INTO palateapp.countrydetails values (26, 'BULGARIA', 359, 'BGN','Bulgarian Lev','BG','');
INSERT INTO palateapp.countrydetails values (27, 'BURKINA FASO', 226, 'XOF','West African CFA Franc','BF','');
INSERT INTO palateapp.countrydetails values (28, 'BURUNDI', 257, 'BIF','Burundian Franc','BI','');
INSERT INTO palateapp.countrydetails values (29, 'CABO VERDE', 238, 'CVE','Cabo Verdean Escudo','CV','');
INSERT INTO palateapp.countrydetails values (30, 'CAMBODIA', 855, 'KHR','Cambodian Riel','KH','');
INSERT INTO palateapp.countrydetails values (31, 'CAMEROON', 237, 'XAF','Central African CFA Franc','CM','');
INSERT INTO palateapp.countrydetails values (32, 'CANADA', 1, 'CAD','Canadian Dollar','CA','');
INSERT INTO palateapp.countrydetails values (33, 'CENTRAL AFRICAN REPUBLIC', 236, 'XAF','Central African CFA Franc','CF','');
INSERT INTO palateapp.countrydetails values (34, 'CHAD', 235, 'XAF','Central African CFA Franc','TD','');
INSERT INTO palateapp.countrydetails values (35, 'CHILE', 56, 'CLP','Chilean Peso','CL','');
INSERT INTO palateapp.countrydetails values (36, 'CHINA', 86, 'CNY','Chinese Yuan','CN','');
INSERT INTO palateapp.countrydetails values (37, 'COLOMBIA', 57, 'COP','Colombian Peso','CO','');
INSERT INTO palateapp.countrydetails values (38, 'COMOROS', 269, 'KMF','Comorian Franc','KM','');
INSERT INTO palateapp.countrydetails values (39, 'CONGO, DEMOCRATIC REPUBLIC OF THE', 243, 'CDF','Congolese Franc','CD','');
INSERT INTO palateapp.countrydetails values (40, 'CONGO, REPUBLIC OF THE', 242, 'XAF','Central African CFA Franc','CG','');
INSERT INTO palateapp.countrydetails values (41, 'COSTA RICA', 506, 'CRC','Costa Rican Colon','CR','');
INSERT INTO palateapp.countrydetails values (42, 'COTE D''IVOIRE', 225, 'XOF','West African CFA Franc','CI','');
INSERT INTO palateapp.countrydetails values (43, 'CROATIA', 385, 'HRK','Croatian Kuna','HR','');
INSERT INTO palateapp.countrydetails values (44, 'CUBA', 53, 'CUP','Cuban Peso','CU','');
INSERT INTO palateapp.countrydetails values (45, 'CYPRUS', 357, 'EUR','Euro','CY','U+20AC');
INSERT INTO palateapp.countrydetails values (46, 'CZECH REPUBLIC', 420, 'CZK','Czech Koruna','CZ','');
INSERT INTO palateapp.countrydetails values (47, 'DENMARK', 45, 'DKK','Danish Krone','DK','');
INSERT INTO palateapp.countrydetails values (48, 'DJIBOUTI', 253, 'DJF','Djiboutian Franc','DJ','');
INSERT INTO palateapp.countrydetails values (49, 'DOMINICA', 1, 'XCD','East Caribbean Dollar','DM','');
INSERT INTO palateapp.countrydetails values (50, 'DOMINICAN REPUBLIC', 1, 'DOP','Dominican Peso','DO','');
INSERT INTO palateapp.countrydetails values (51, 'ECUADOR', 593, 'USD','United States Dollar','EC','');
INSERT INTO palateapp.countrydetails values (52, 'EGYPT', 20, 'EGP','Egyptian Pound','EG','');
INSERT INTO palateapp.countrydetails values (53, 'EL SALVADOR', 503, 'USD','United States Dollar','SV','');
INSERT INTO palateapp.countrydetails values (54, 'EQUATORIAL GUINEA', 240, 'XAF','Central African CFA Franc','GQ','');
INSERT INTO palateapp.countrydetails values (55, 'ERITREA', 291, 'ERN','Eritrean Nakfa','ER','');
INSERT INTO palateapp.countrydetails values (56, 'ESTONIA', 372, 'EUR','Euro','EE','U+20AC');
INSERT INTO palateapp.countrydetails values (57, 'ESWATINI', 268, 'SZL','Swazi Lilangeni','SZ','');
INSERT INTO palateapp.countrydetails values (58, 'ETHIOPIA', 251, 'ETB','Ethiopian Birr','ET','');
INSERT INTO palateapp.countrydetails values (59, 'FIJI', 679, 'FJD','Fijian Dollar','FJ','');
INSERT INTO palateapp.countrydetails values (60, 'FINLAND', 358, 'EUR','Euro','FI','U+20AC');
INSERT INTO palateapp.countrydetails values (61, 'FRANCE', 33, 'EUR','Euro','FR','U+20AC');
INSERT INTO palateapp.countrydetails values (62, 'GABON', 241, 'XAF','Central African CFA Franc','GA','');
INSERT INTO palateapp.countrydetails values (63, 'GAMBIA', 220, 'GMD','Gambian Dalasi','GM','');
INSERT INTO palateapp.countrydetails values (64, 'GEORGIA', 995, 'GEL','Georgian Lari','GE','');
INSERT INTO palateapp.countrydetails values (65, 'GERMANY', 49, 'EUR','Euro','DE','U+20AC');
INSERT INTO palateapp.countrydetails values (66, 'GHANA', 233, 'GHS','Ghanaian Cedi','GH','');
INSERT INTO palateapp.countrydetails values (67, 'GIBRALTAR', 350, 'GIP','Gibraltar Pound','GI','');
INSERT INTO palateapp.countrydetails values (68, 'GREECE', 30, 'EUR','Euro','GR','U+20AC');
INSERT INTO palateapp.countrydetails values (69, 'GRENADA', 1, 'XCD','East Caribbean Dollar','GD','');
INSERT INTO palateapp.countrydetails values (70, 'GUATEMALA', 502, 'GTQ','Guatemalan Quetzal','GT','');
INSERT INTO palateapp.countrydetails values (71, 'GUINEA', 224, 'GNF','Guinean Franc','GN','');
INSERT INTO palateapp.countrydetails values (72, 'GUINEA-BISSAU', 245, 'XOF','West African CFA Franc','GW','');
INSERT INTO palateapp.countrydetails values (73, 'GUYANA', 592, 'GYD','Guyanese Dollar','GY','');
INSERT INTO palateapp.countrydetails values (74, 'HAITI', 509, 'HTG','Haitian Gourde','HT','');
INSERT INTO palateapp.countrydetails values (75, 'HONDURAS', 504, 'HNL','Honduran Lempira','HN','');
INSERT INTO palateapp.countrydetails values (76, 'HUNGARY', 36, 'HUF','Hungarian Forint','HU','');
INSERT INTO palateapp.countrydetails values (77, 'ICELAND', 354, 'ISK','Icelandic Krona','IS','');
INSERT INTO palateapp.countrydetails values (78, 'INDIA', 91, 'INR','Indian Rupee','IN','U+20B9');
INSERT INTO palateapp.countrydetails values (79, 'INDONESIA', 62, 'IDR','Indonesian Rupiah','ID','');
INSERT INTO palateapp.countrydetails values (80, 'IRAN', 98, 'IRR','Iranian Rial','IR','');
INSERT INTO palateapp.countrydetails values (81, 'IRAQ', 964, 'IQD','Iraqi Dinar','IQ','');
INSERT INTO palateapp.countrydetails values (82, 'IRELAND', 353, 'EUR','Euro','IE','U+20AC');
INSERT INTO palateapp.countrydetails values (83, 'ISLE OF MAN', 44, 'GBP','British Pound','IM','U+00A3');
INSERT INTO palateapp.countrydetails values (84, 'ISRAEL', 972, 'ILS','Israeli Shekel','IL','');
INSERT INTO palateapp.countrydetails values (85, 'ITALY', 39, 'EUR','Euro','IT','U+20AC');
INSERT INTO palateapp.countrydetails values (86, 'JAMAICA', 1, 'JMD','Jamaican Dollar','JM','');
INSERT INTO palateapp.countrydetails values (87, 'JAPAN', 81, 'JPY','Japanese Yen','JP','');
INSERT INTO palateapp.countrydetails values (88, 'JORDAN', 962, 'JOD','Jordanian Dinar','JO','');
INSERT INTO palateapp.countrydetails values (89, 'KAZAKHSTAN', 7, 'KZT','Kazakhstani Tenge','KZ','');
INSERT INTO palateapp.countrydetails values (90, 'KENYA', 254, 'KES','Kenyan Shilling','KE','');
INSERT INTO palateapp.countrydetails values (91, 'KIRIBATI', 686, 'AUD','Australian Dollar','KI','');
INSERT INTO palateapp.countrydetails values (92, 'KOSOVO', 383, 'EUR','Euro','XK','U+20AC');
INSERT INTO palateapp.countrydetails values (93, 'KUWAIT', 965, 'KWD','Kuwaiti Dinar','KW','');
INSERT INTO palateapp.countrydetails values (94, 'KYRGYZSTAN', 996, 'KGS','Kyrgyzstani Som','KG','');
INSERT INTO palateapp.countrydetails values (95, 'LAOS', 856, 'LAK','Lao Kip','LA','');
INSERT INTO palateapp.countrydetails values (96, 'LATVIA', 371, 'EUR','Euro','LV','U+20AC');
INSERT INTO palateapp.countrydetails values (97, 'LEBANON', 961, 'LBP','Lebanese Pound','LB','');
INSERT INTO palateapp.countrydetails values (98, 'LESOTHO', 266, 'LSL','Lesotho Loti','LS','');
INSERT INTO palateapp.countrydetails values (99, 'LIBERIA', 231, 'LRD','Liberian Dollar','LR','');
INSERT INTO palateapp.countrydetails values (100, 'LIBYA', 218, 'LYD','Libyan Dinar','LY','');
INSERT INTO palateapp.countrydetails values (101, 'LIECHTENSTEIN', 423, 'CHF','Swiss Franc','LI','');
INSERT INTO palateapp.countrydetails values (102, 'LITHUANIA', 370, 'EUR','Euro','LT','U+20AC');
INSERT INTO palateapp.countrydetails values (103, 'LUXEMBOURG', 352, 'EUR','Euro','LU','U+20AC');
INSERT INTO palateapp.countrydetails values (104, 'MADAGASCAR', 261, 'MGA','Malagasy Ariary','MG','');
INSERT INTO palateapp.countrydetails values (105, 'MALAWI', 265, 'MWK','Malawian Kwacha','MW','');
INSERT INTO palateapp.countrydetails values (106, 'MALAYSIA', 60, 'MYR','Malaysian Ringgit','MY','');
INSERT INTO palateapp.countrydetails values (107, 'MALDIVES', 960, 'MVR','Maldivian Rufiyaa','MV','');
INSERT INTO palateapp.countrydetails values (108, 'MALI', 223, 'XOF','West African CFA Franc','ML','');
INSERT INTO palateapp.countrydetails values (109, 'MALTA', 356, 'EUR','Euro','MT','U+20AC');
INSERT INTO palateapp.countrydetails values (110, 'MARSHALL ISLANDS', 692, 'USD','United States Dollar','MH','');
INSERT INTO palateapp.countrydetails values (111, 'MAURITANIA', 222, 'MRU','Mauritanian Ouguiya','MR','');
INSERT INTO palateapp.countrydetails values (112, 'MAURITIUS', 230, 'MUR','Mauritian Rupee','MU','');
INSERT INTO palateapp.countrydetails values (113, 'MEXICO', 52, 'MXN','Mexican Peso','MX','');
INSERT INTO palateapp.countrydetails values (114, 'MICRONESIA', 691, 'USD','United States Dollar','FM','');
INSERT INTO palateapp.countrydetails values (115, 'MOLDOVA', 373, 'MDL','Moldovan Leu','MD','');
INSERT INTO palateapp.countrydetails values (116, 'MONACO', 377, 'EUR','Euro','MC','U+20AC');
INSERT INTO palateapp.countrydetails values (117, 'MONGOLIA', 976, 'MNT','Mongolian Tugrik','MN','');
INSERT INTO palateapp.countrydetails values (118, 'MONTENEGRO', 382, 'EUR','Euro','ME','U+20AC');
INSERT INTO palateapp.countrydetails values (119, 'MOROCCO', 212, 'MAD','Moroccan Dirham','MA','');
INSERT INTO palateapp.countrydetails values (120, 'MOZAMBIQUE', 258, 'MZN','Mozambican Metical','MZ','');
INSERT INTO palateapp.countrydetails values (121, 'MYANMAR', 95, 'MMK','Myanmar Kyat','MM','');
INSERT INTO palateapp.countrydetails values (122, 'NAMIBIA', 264, 'NAD','Namibian Dollar','NA','');
INSERT INTO palateapp.countrydetails values (123, 'NAURU', 674, 'AUD','Australian Dollar','NR','');
INSERT INTO palateapp.countrydetails values (124, 'NEPAL', 977, 'NPR','Nepalese Rupee','NP','');
INSERT INTO palateapp.countrydetails values (125, 'NETHERLANDS', 31, 'EUR','Euro','NL','U+20AC');
INSERT INTO palateapp.countrydetails values (126, 'NEW ZEALAND', 64, 'NZD','New Zealand Dollar','NZ','');
INSERT INTO palateapp.countrydetails values (127, 'NICARAGUA', 505, 'NIO','Nicaraguan Cordoba','NI','');
INSERT INTO palateapp.countrydetails values (128, 'NIGER', 227, 'XOF','West African CFA Franc','NE','');
INSERT INTO palateapp.countrydetails values (129, 'NIGERIA', 234, 'NGN','Nigerian Naira','NG','');
INSERT INTO palateapp.countrydetails values (130, 'NORTH KOREA', 850, 'KPW','North Korean Won','KP','');
INSERT INTO palateapp.countrydetails values (131, 'NORTH MACEDONIA', 389, 'MKD','Macedonian Denar','MK','');
INSERT INTO palateapp.countrydetails values (132, 'NORWAY', 47, 'NOK','Norwegian Krone','NO','');
INSERT INTO palateapp.countrydetails values (133, 'OMAN', 968, 'OMR','Omani Rial','OM','');
INSERT INTO palateapp.countrydetails values (134, 'PAKISTAN', 92, 'PKR','Pakistani Rupee','PK','');
INSERT INTO palateapp.countrydetails values (135, 'PALAU', 680, 'USD','United States Dollar','PW','');
INSERT INTO palateapp.countrydetails values (136, 'PALESTINE', 970, 'ILS','Israeli Shekel','PS','');
INSERT INTO palateapp.countrydetails values (137, 'PANAMA', 507, 'PAB','Panamanian Balboa','PA','');
INSERT INTO palateapp.countrydetails values (138, 'PAPUA NEW GUINEA', 675, 'PGK','Papua New Guinean Kina','PG','');
INSERT INTO palateapp.countrydetails values (139, 'PARAGUAY', 595, 'PYG','Paraguayan Guarani','PY','');
INSERT INTO palateapp.countrydetails values (140, 'PERU', 51, 'PEN','Peruvian Sol','PE','');
INSERT INTO palateapp.countrydetails values (141, 'PHILIPPINES', 63, 'PHP','Philippine Peso','PH','');
INSERT INTO palateapp.countrydetails values (142, 'POLAND', 48, 'PLN','Polish Zloty','PL','');
INSERT INTO palateapp.countrydetails values (143, 'PORTUGAL', 351, 'EUR','Euro','PT','U+20AC');
INSERT INTO palateapp.countrydetails values (144, 'QATAR', 974, 'QAR','Qatari Riyal','QA','');
INSERT INTO palateapp.countrydetails values (145, 'ROMANIA', 40, 'RON','Romanian Leu','RO','');
INSERT INTO palateapp.countrydetails values (146, 'RUSSIA', 7, 'RUB','Russian Ruble','RU','');
INSERT INTO palateapp.countrydetails values (147, 'RWANDA', 250, 'RWF','Rwandan Franc','RW','');
INSERT INTO palateapp.countrydetails values (148, 'SAINT KITTS AND NEVIS', 1, 'XCD','East Caribbean Dollar','KN','');
INSERT INTO palateapp.countrydetails values (149, 'SAINT LUCIA', 1, 'XCD','East Caribbean Dollar','LC','');
INSERT INTO palateapp.countrydetails values (150, 'SAINT VINCENT AND THE GRENADINES', 1, 'XCD','East Caribbean Dollar','VC','');
INSERT INTO palateapp.countrydetails values (151, 'SAMOA', 685, 'WST','Samoan Tala','WS','');
INSERT INTO palateapp.countrydetails values (152, 'SAN MARINO', 378, 'EUR','Euro','SM','U+20AC');
INSERT INTO palateapp.countrydetails values (153, 'SAO TOME AND PRINCIPE', 239, 'STN','Sao Tome and Principe Dobra','ST','');
INSERT INTO palateapp.countrydetails values (154, 'SAUDI ARABIA', 966, 'SAR','Saudi Riyal','SA','');
INSERT INTO palateapp.countrydetails values (155, 'SENEGAL', 221, 'XOF','West African CFA Franc','SN','');
INSERT INTO palateapp.countrydetails values (156, 'SERBIA', 381, 'RSD','Serbian Dinar','RS','');
INSERT INTO palateapp.countrydetails values (157, 'SEYCHELLES', 248, 'SCR','Seychellois Rupee','SC','');
INSERT INTO palateapp.countrydetails values (158, 'SIERRA LEONE', 232, 'SLL','Sierra Leonean Leone','SL','');
INSERT INTO palateapp.countrydetails values (159, 'SINGAPORE', 65, 'SGD','Singapore Dollar','SG','');
INSERT INTO palateapp.countrydetails values (160, 'SLOVAKIA', 421, 'EUR','Euro','SK','U+20AC');
INSERT INTO palateapp.countrydetails values (161, 'SLOVENIA', 386, 'EUR','Euro','SI','U+20AC');
INSERT INTO palateapp.countrydetails values (162, 'SOLOMON ISLANDS', 677, 'SBD','Solomon Islands Dollar','SB','');
INSERT INTO palateapp.countrydetails values (163, 'SOMALIA', 252, 'SOS','Somali Shilling','SO','');
INSERT INTO palateapp.countrydetails values (164, 'SOUTH AFRICA', 27, 'ZAR','South African Rand','ZA','');
INSERT INTO palateapp.countrydetails values (165, 'SOUTH KOREA', 82, 'KRW','South Korean Won','KR','');
INSERT INTO palateapp.countrydetails values (166, 'SOUTH SUDAN', 211, 'SSP','South Sudanese Pound','SS','');
INSERT INTO palateapp.countrydetails values (167, 'SPAIN', 34, 'EUR','Euro','ES','U+20AC');
INSERT INTO palateapp.countrydetails values (168, 'SRI LANKA', 94, 'LKR','Sri Lankan Rupee','LK','');
INSERT INTO palateapp.countrydetails values (169, 'SUDAN', 249, 'SDG','Sudanese Pound','SD','');
INSERT INTO palateapp.countrydetails values (170, 'SURINAME', 597, 'SRD','Surinamese Dollar','SR','');
INSERT INTO palateapp.countrydetails values (171, 'SWEDEN', 46, 'SEK','Swedish Krona','SE','');
INSERT INTO palateapp.countrydetails values (172, 'SWITZERLAND', 41, 'CHF','Swiss Franc','CH','');
INSERT INTO palateapp.countrydetails values (173, 'SYRIA', 963, 'SYP','Syrian Pound','SY','');
INSERT INTO palateapp.countrydetails values (174, 'TAIWAN', 886, 'TWD','New Taiwan Dollar','TW','');
INSERT INTO palateapp.countrydetails values (175, 'TAJIKISTAN', 992, 'TJS','Tajikistani Somoni','TJ','');
INSERT INTO palateapp.countrydetails values (176, 'TANZANIA', 255, 'TZS','Tanzanian Shilling','TZ','');
INSERT INTO palateapp.countrydetails values (177, 'THAILAND', 66, 'THB','Thai Baht','TH','');
INSERT INTO palateapp.countrydetails values (178, 'TIMOR-LESTE', 670, 'USD','United States Dollar','TL','');
INSERT INTO palateapp.countrydetails values (179, 'TOGO', 228, 'XOF','West African CFA Franc','TG','');
INSERT INTO palateapp.countrydetails values (180, 'TONGA', 676, 'TOP','Tongan Pa''anga','TO','');
INSERT INTO palateapp.countrydetails values (181, 'TRINIDAD AND TOBAGO', 1, 'TTD','Trinidad and Tobago Dollar','TT','');
INSERT INTO palateapp.countrydetails values (182, 'TUNISIA', 216, 'TND','Tunisian Dinar','TN','');
INSERT INTO palateapp.countrydetails values (183, 'TURKEY', 90, 'TRY','Turkish Lira','TR','');
INSERT INTO palateapp.countrydetails values (184, 'TURKMENISTAN', 993, 'TMT','Turkmenistan Manat','TM','');
INSERT INTO palateapp.countrydetails values (185, 'TUVALU', 688, 'AUD','Australian Dollar','TV','');
INSERT INTO palateapp.countrydetails values (186, 'UGANDA', 256, 'UGX','Ugandan Shilling','UG','');
INSERT INTO palateapp.countrydetails values (187, 'UKRAINE', 380, 'UAH','Ukrainian Hryvnia','UA','');
INSERT INTO palateapp.countrydetails values (188, 'UNITED ARAB EMIRATES', 971, 'AED','United Arab Emirates Dirham','AE','');
INSERT INTO palateapp.countrydetails values (189, 'UNITED KINGDOM', 44, 'GBP','British Pound','GB','U+00A3');
INSERT INTO palateapp.countrydetails values (190, 'UNITED STATES', 1, 'USD','United States Dollar','US','');
INSERT INTO palateapp.countrydetails values (191, 'URUGUAY', 598, 'UYU','Uruguayan Peso','UY','');
INSERT INTO palateapp.countrydetails values (192, 'UZBEKISTAN', 998, 'UZS','Uzbekistani Som','UZ','');
INSERT INTO palateapp.countrydetails values (193, 'VANUATU', 678, 'VUV','Vanuatu Vatu','VU','');
INSERT INTO palateapp.countrydetails values (194, 'VATICAN CITY', 379, 'EUR','Euro','VA','U+20AC');
INSERT INTO palateapp.countrydetails values (195, 'VENEZUELA', 58, 'VES','Venezuelan Bolivar','VE','');
INSERT INTO palateapp.countrydetails values (196, 'VIETNAM', 84, 'VND','Vietnamese Dong','VN','');
INSERT INTO palateapp.countrydetails values (197, 'YEMEN', 967, 'YER','Yemeni Rial','YE','');
INSERT INTO palateapp.countrydetails values (198, 'ZAMBIA', 260, 'ZMW','Zambian Kwacha','ZM','');
INSERT INTO palateapp.countrydetails values (199, 'ZIMBABWE', 263, 'ZWL','Zimbabwean Dollar','ZW','');
