name: Start or Stop Palate Dev ECS Services on cron

on:
  schedule:
    - cron: '30 15 * * *'
    - cron: '30 3 * * 1,2,3,4,5'
  workflow_dispatch:
    inputs:
      actiontoperform:
        description: 'Action To Perform'     
        type: choice
        default: 'None'
        options:
          - None
          - Stop
          - Start

env:
  ACTION_TO_PERFORM: ${{ github.event.inputs.actiontoperform }}
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Start ECS Services
      if: ${{ github.event.schedule == '30 4 * * 1,2,3,4,5' || env.ACTION_TO_PERFORM == 'Start' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecs update-service --service common-data-api-service-new --cluster palate-app-dev-cluster --desired-count 1 --force-new-deployment
        aws ecs update-service --service review-api-service --cluster palate-app-dev-cluster --desired-count 1 --force-new-deployment
        aws ecs update-service --service search-reviews-api-service --cluster palate-app-dev-cluster --desired-count 1 --force-new-deployment
        aws ecs update-service --service palate-user-api-service --cluster palate-app-dev-cluster --desired-count 1 --force-new-deployment

    - name: Stop ECS Services
      if: ${{ github.event.schedule == '30 15 * * *' || env.ACTION_TO_PERFORM == 'Stop'}}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecs update-service --service common-data-api-service-new --cluster palate-app-dev-cluster --desired-count 0 --force-new-deployment
        aws ecs update-service --service review-api-service --cluster palate-app-dev-cluster --desired-count 0 --force-new-deployment
        aws ecs update-service --service search-reviews-api-service --cluster palate-app-dev-cluster --desired-count 0 --force-new-deployment
        aws ecs update-service --service palate-user-api-service --cluster palate-app-dev-cluster --desired-count 0 --force-new-deployment
